# Generated by Django 3.2 on 2024-05-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_music', models.IntegerField()),
                ('name_music', models.CharField(max_length=200)),
                ('music', models.FileField(upload_to='music_files/')),
                ('name_singer', models.CharField(max_length=200)),
                ('release_year', models.CharField(max_length=10)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
