# Generated by Django 3.2 on 2024-05-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0002_auto_20240518_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id_music',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
