# Generated by Django 3.2 on 2024-05-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='id',
        ),
        migrations.AlterField(
            model_name='music',
            name='id_music',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
