# Generated by Django 3.2 on 2024-05-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0003_alter_music_id_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='music_images/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(choices=[('POP', 'Pop'), ('ROCK', 'Rock'), ('JAZZ', 'Jazz'), ('CLASSICAL', 'Classical'), ('HIPHOP', 'Hip-Hop'), ('REMIX', 'Remix'), ('ROMANCE', 'Romance'), ('BOLERO', 'Bolero')], max_length=100, verbose_name='Genre'),
        ),
    ]
