# Generated by Django 3.2 on 2024-05-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0005_auto_20240519_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='username',
        ),
        migrations.AddField(
            model_name='transaction',
            name='user_id_tran',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MusicApp.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='role_id_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MusicApp.role'),
        ),
        migrations.AddField(
            model_name='vote',
            name='user_id_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MusicApp.user'),
        ),
        migrations.AlterField(
            model_name='singer',
            name='email_singer',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_user',
            field=models.EmailField(max_length=50),
        ),
    ]
