# Generated by Django 3.2 on 2024-05-20 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MusicApp', '0006_auto_20240519_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='status_music',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='status_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='music_id_vote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MusicApp.music'),
        ),
    ]
